// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOyQl6glVRgeXU20du_PLDEpIhvFGSDPg',
    appId: '1:647272816114:web:e2c9ed7b794f7f527b1f6b',
    messagingSenderId: '647272816114',
    projectId: 'hotel-primavera-cafd9',
    authDomain: 'hotel-primavera-cafd9.firebaseapp.com',
    storageBucket: 'hotel-primavera-cafd9.appspot.com',
    databaseURL: 'https://hotel-primavera-cafd9-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeTyveszO6sf7zU-4G7jGhwGSlbcPr2fs',
    appId: '1:647272816114:android:b8001b6eff4c0c2f7b1f6b',
    messagingSenderId: '647272816114',
    projectId: 'hotel-primavera-cafd9',
    storageBucket: 'hotel-primavera-cafd9.appspot.com',
    databaseURL: 'https://hotel-primavera-cafd9-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt4AqE7i3tG78-aPegOfvLePdskyDORaQ',
    appId: '1:647272816114:ios:167a8ee1946977317b1f6b',
    messagingSenderId: '647272816114',
    projectId: 'hotel-primavera-cafd9',
    storageBucket: 'hotel-primavera-cafd9.appspot.com',
    iosClientId:
        '647272816114-sn4qrs0ni4bq1n11o3mfdop2d5604676.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotelPrimaveraApp',
    databaseURL: 'https://hotel-primavera-cafd9-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt4AqE7i3tG78-aPegOfvLePdskyDORaQ',
    appId: '1:647272816114:ios:167a8ee1946977317b1f6b',
    messagingSenderId: '647272816114',
    projectId: 'hotel-primavera-cafd9',
    storageBucket: 'hotel-primavera-cafd9.appspot.com',
    iosClientId:
        '647272816114-sn4qrs0ni4bq1n11o3mfdop2d5604676.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotelPrimaveraApp',
    databaseURL: 'https://hotel-primavera-cafd9-default-rtdb.firebaseio.com/',
  );
}
